# Site wide configuration

title:            Theron's Blog
locale:           en_US
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Chu Xiaotian
  avatar: avatar.jpg
  bio: "Remember that day, remember that feel."
  email: theron.chu@gmail.com
  disqus-shortname: CHN-XCHU
  facebook: theron.chu@gmail.com
  google:
    plus: theron.chu@gmail.com
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: tracytheron
  stackoverflow: http://stackoverflow.com/users/1921007/tracy-theron
  linkedin: #username
  xing: #username
  instagram: tracytheron
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: keylovelock
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
